### ISSUE TITLE
Hidden Form Field

### ISSUE THREAD

**Issue by thanegill** [SjonHortensius/pfsense#10]
Need an option to hide a form field. 

Can currently hide the `<input>` tag but not the `<label>` tag.

Refrence: https://github.com/SjonHortensius/pfsense/pull/9/files#r25847749

**Comment by SjonHortensius** [comment]
To clarify, addInput is simply a shortcut for new Group()->add($input) which takes it's label from the inputs name. It will always render a <label> and doesn't currently look at the actual inputs it contains.

Group has however been prepared for this, and should use Element's classes to hide itself
