### ISSUE TITLE
Update display_top_tabs to use pills as default

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [SjonHortensius/pfsense#107]
The default used to be 'tabs', but from a layout point of view I've already chosen that pills should be the default.

**Comment by SanderVanLeeuwen** [comment]
FYI @sbeaver-netgate & @psophis I've updated the default. If there's a case where you'd like to make an exception and use tabs instead, you can supply the type argument. For the main action navigation though, this should always be 'pills' navigation.

**Comment by sbeaver-netgate** [comment]
Looks good. Thank you.

The pages I have worked on and that had tabs render correctly with pills and look attractive.

## Steve

Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com mailto:sbeaver@netgate.com | www.netgate.com http://www.netgate.com/

**Comment by SjonHortensius** [comment]
Looks good
