### ISSUE TITLE
Collapse for selects is a bit trigger happy

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [SjonHortensius/pfsense#108]
Try the 'type' selector at system_authservers.php?act=new for example. Almost toggles panels when you even look at it ;)

**Comment by SjonHortensius** [comment]
Pretty sure this happens because of the big panel it toggles. For me, the Radius-toggle looks fine but the LDAP toggle is a bit aggressive. Is this different for you?

**Comment by sbeaver-netgate** [comment]
On OS-X Firefox, Safari & Chrome click the type selector but do not move the mouse (ie do not actually make  a selection)  and the LDAP/RADIUS panels toggle seemingly randomly. Then when a selection is actually made, the wrong panel is collapsed.

I see a similar issue with diag_logs_settings and submitted a PR reverting that to PHP toggling.

**Comment by SjonHortensius** [comment]
Yes, I can reproduce that, interesting

**Comment by SjonHortensius** [comment]
So after debugging both bootstrap and jquery way too deep (at least I now know how custom events are dispatched..) I realized this was simply a bug in system_authservers, that had toggle-type set to both sections; meaning it toggles 'randomly' on every click, instead of onchange
