### ISSUE TITLE
Cancel Button in Form

### ISSUE THREAD

**Issue by thanegill** [SjonHortensius/pfsense#11]
Need an option to add a cancel button to a form. For cases where the user is redirected to another page to edit an item.

Could be as simple as adding

``` php
<a role="button" class="btn btn-default" href="<?=$referer;?>"><?=gettext("Cancel"); ?></a>
```

to the `from-group`. with something like this:

``` php
$form->addCancel();

or 

$form->addCancel($referer);
```

Refrence: https://github.com/SjonHortensius/pfsense/pull/9/files#r25847749

**Comment by SjonHortensius** [comment]
fixed in ee0278641

**Comment by thanegill** [comment]
How can you add a cancel button with an input tag?

**Comment by SjonHortensius** [comment]
You're right; this needs more attention. I'll look into it
