### ISSUE TITLE
Make Forms / inputs less wide

### ISSUE THREAD

**Issue by SjonHortensius** [SjonHortensius/pfsense#141]
Currently they are stretched to the max; which is unnecessary. I'm not sure what a better value would be, but I think it might be as low as ~ 6. I will prepare for making this consistent by moving some variables to consts (eg. we never want to vary labelWidth, and 12 should also be a const)

**Comment by SanderVanLeeuwen** [comment]
After playing around with some different values, I feel that changing the column width isn't necessarily the best option. The disadvantage of changing the column width is that the help labels also get resized. As a result, pages are getting longer and longer. 

I've implemented a different solution which resizes the `.form-control`, but keeps the full column available for help labels and other stuff. Feel free to revert if you don't like it, but I think this is the best solution :)

The attached screenshots illustrate the difference between a col-6 and the CSS resize solution.

![screenshot 2015-06-07 11 24 04](https://cloud.githubusercontent.com/assets/1685007/8023345/01001b28-0d09-11e5-8dd0-bbe3718c82f6.png)
![screenshot 2015-06-07 11 15 39](https://cloud.githubusercontent.com/assets/1685007/8023346/01005a48-0d09-11e5-86df-830458f19075.png)
