### ISSUE TITLE
Multiple buttons in form need spacing

### ISSUE THREAD

**Issue by SjonHortensius** [SjonHortensius/pfsense#19]
![screenshot-2043](https://cloud.githubusercontent.com/assets/1684987/6545784/92f97b04-c598-11e4-813d-01b8b064c558.png)

**Comment by SjonHortensius** [comment]
@SanderVanLeeuwen can you verify this fix?

**Comment by SanderVanLeeuwen** [comment]
Isn't it better to use a space or newline (which'll translate to a space) for spacing, like in the Bootstrap examples? http://getbootstrap.com/css/#buttons

If you do choose to use margin, it should at least be applied on `.btn` instead of `input.btn` to support other button elements as well.
