### ISSUE TITLE
Multi-select input size

### ISSUE THREAD

**Issue by sbeaver-netgate** [SjonHortensius/pfsense#197]
If a Form_Select element is selected and multiselect is specified, the resulting element appears to be of incorrect size. In this example you can see from teh print_r that there is only one option available and none are selected, yet the input element appears to be three rows high.

![pfsense_localdomain_-_interfacesbridgeedit](https://cloud.githubusercontent.com/assets/11539696/7571741/9c6a6d02-f7e7-11e4-927e-28b99944b361.png)

**Comment by SjonHortensius** [comment]
I actually don't think this is a problem. Would you expect a 1 line-high select?

**Comment by SanderVanLeeuwen** [comment]
Agreed. From a UX standpoint, users won't expect an select of only one line. I think this is the expected and correct behaviour.

**Comment by sbeaver-netgate** [comment]
If there are two, or three items to select from, why present a four high control?

## Steve

Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com | www.netgate.com
