### ISSUE TITLE
Need a way to nest Form_Groups

### ISSUE THREAD

**Issue by thanegill** [SjonHortensius/pfsense#20]
I have a case where a group is needed to be hidden under section configuration circumstances, but also has radio buttons as a sub group.

**Comment by SanderVanLeeuwen** [comment]
I'm not exactly sure what you mean. Can you provide a screenshot or refer to a specific file?

**Comment by thanegill** [comment]
I think I figured out for to get around this, Not as issue any more.

**Comment by thanegill** [comment]
Reopening This is what I was running into. 
![image](https://cloud.githubusercontent.com/assets/1141680/6580249/7bf3b436-c70c-11e4-943e-2721f11f0be4.png)

As you see in the "Lease Requirements and request" they are a separate then everything else, but apart of the "DHCP Client Configuration" section. I can add a full new separate section form them which I have done already. But doing so creates more issues with collapsing sections than it's worth.

**Comment by SjonHortensius** [comment]
What is wrong with this setup?

``` php
$group = new Form_Group('Lease Requirements and request');
$group->add(new Form_Input(...));
$group->add(new Form_Input(...));
$group->add(new Form_Input(...));
$group->add(new Form_Input(...));
```

**Comment by thanegill** [comment]
When Inputs are in a group their label is not shown, I think that's really what needs to be fixed. So more of a labeling issue and not a group nesting issue.

Example:

![image](https://cloud.githubusercontent.com/assets/1141680/6580516/59ab6a02-c70e-11e4-82e9-a8b3501d9597.png)

(What's show below each Input is from `setHelp()`)

**Comment by SjonHortensius** [comment]
Okay, and what about moving it to a separate Section? (same goes for Protocol Timing block)? I think the toggleability should work the same (not sure)?

**Comment by thanegill** [comment]
It works if only one input is toggling it. In this case I have two (The IPv(4/6) Configuration type and the advanced DHCP checkbox).

**Comment by SjonHortensius** [comment]
Okay, if the _IPv4 Configuration Type_ toggles the entire Section; then you can add a Checkbox for the advanced options (as a regular Input).

If you then add the 'advanced' class to the inputs you want to hide you can make the checkbox toggle them.

``` php
$section->addInput(new Form_Checkbox(
    'show_advanced',
    'Advanced',
    'Show advanced options'
))->setAttribute('data-toggle', 'collapse')->setAttribute('data-target', '.toggle-advanced');;

/* ... */

$group->add(new Form_Input(
    'stuff',
    'Normally hidden advanced input',
    /* stuff */
))->addClass('toggle-advanced collapse');

$group->add(new Form_Input(
    'stuff',
    'Normally hidden advanced input',
    /* stuff */
))->addClass('toggle-advanced collapse');
```

I did a similar setup for /system_authservers.php?act=new (check out _Extended query_ & _Anonymous bind_)
