### ISSUE TITLE
`data-toggle` to Hide Section or Group

### ISSUE THREAD

**Issue by thanegill** [SjonHortensius/pfsense#21]
Need a way to use the attribute `data-toggle` to hide a `Form_Group` or `Form_Section`.

**Comment by SanderVanLeeuwen** [comment]
You can manually create a group and add the relevant classes:

```
$section->addInput(new Form_Checkbox(
    '...'
))->setAttribute('data-toggle', 'collapse')->setAttribute('data-target', '.toggle-input_name');

$group = new Form_Group('');
$group->addClass('toggle-input_name collapse');

if (!empty($pconfig['input_name_enable']))
    $group->addClass('in');

$group->add(new Form_Input(
    '...'
));

$section->add($group);
```

It's probably better to create an helper on the section which accepts a toggle attribute and assigns it to the relevant groups and inputs, but I'll leve it to @SjonHortensius to tackle that ;)

**Comment by SjonHortensius** [comment]
I think I'll introduce a Form_GroupToggleable that has a setHandler($input, $openByDefault = true) method to handle this, thoughts?

**Comment by SanderVanLeeuwen** [comment]
Actually, the only thing necessary is the toggle class (and status, 'in' for active) on the input's parent group. So I was thinking about a helper on the Form_Input, which sets a specified class on the group it's in?

Something like:

```
$section->addInput(new Form_Input('...'
))->setGroupClass('toggle-input_name');
```

The upside is that you won't have to manually create a group. The downside is that it would still require a manual check on the current status wether to start collapsed or opened.

**Comment by thanegill** [comment]
What will be displayed when "collapsed", will the group title still be visible? If so I don't think that will work for `interfaces.php` as there are 20-30 groups, maybe more, don't know, I haven't finished yet. Got another 1500 lines to go...

**Comment by SanderVanLeeuwen** [comment]
Do you mean the group or section title? Sounds like you might want to hide a whole section, instead of just an input group?

I've implemented the above example in `vpn_ipsec_mobile.php`. For example, the 'DNS Servers' checkbox toggles 4 corresponding input groups.

**Comment by thanegill** [comment]
Yes, I ment section. But there are a few cases where I would need to hide a input group as well.

Is it currently possible for a select to unhide/hide multiple groups or sections?

**Comment by SanderVanLeeuwen** [comment]
Yes, the example I gave does that. The `data-target` attribute on the element you're using to toggle accepts any CSS selector, in this case a class. Any element you give this class, gets toggled. So, adding this class to multiple groups or sections (or other elements, if you wish) results in them getting toggled.

**Comment by thanegill** [comment]
How would you start one collapsed and one not, swapping the collapsed group states with the checkbox?

Is that as simple as not adding the `collapse` class to the group?

**Comment by thanegill** [comment]
Answered my own question. Didn't know that this was a [part of Bootstrap](http://getbootstrap.com/javascript/#collapse).

The one part that I don't know how to approach is how to collapse sections using a select dropdown. I can be done. I just think that I'll need to be able to add attributes to each `<option>` tag and I don't believe we can do that yet.

One option is to be able to pass `addItem()` raw HTML that it could add to the section. I'll open a new ticket for that as a request though. (Opened #27)

**Comment by SanderVanLeeuwen** [comment]
Ah yes, I forgot to mention the Bootstrap docs.

Toggle won't work with `<option>` though. Selecting an option doesn't trigger a click event. I can whip up some custom JS to add this behaviour?

**Comment by thanegill** [comment]
That would be great if you did that. For reference, this is for the interfaces page where what type of IPv(4/6) configuration type will toggle certain elements.

[This is how it's implemented now](https://github.com/SjonHortensius/pfsense/blob/a707f00bb7e462bc91d0ea11e950fd147c4ed6df/usr/local/www/interfaces.php#L1427)
[And the select element](https://github.com/SjonHortensius/pfsense/blob/a707f00bb7e462bc91d0ea11e950fd147c4ed6df/usr/local/www/interfaces.php#L1668)

**Comment by SanderVanLeeuwen** [comment]
The related commit adds a global method which binds the collapsable behaviour to options as well. Might have to discuss the codestyle with @SjonHortensius, but the idea stays the same.

When `data-toggle="collapsed"` is attached to a select, it uses the selected option's value to find a related group or section to toggle. So in this (still very verbose) example, one of the `toggle-example_x` groups is toggled when selected. You can ofcourse toggle sections instead of groups.

```
$section->addInput(new Form_Select(
    'toggle_inputs',
    'Toggle inputs',
    'example_2', // Current value
    array(
        'example_1' => 'Something',
        'example_2' => 'Something different',
        'example_3' => 'Something different entirely',
    )
))->setHelp('Source')->setAttribute('data-toggle', 'collapse');

$group = new Form_Group('Input 1');
$group->addClass('toggle-example_1 collapse');

$group->add(new Form_Input(
    'input_name', // Does not have to match toggle class (!)
    'Input 1',
    'text',
    ''
));

$section->add($group);

$group = new Form_Group('Input 2');
$group->addClass('toggle-example_2 collapse');

$group->add(new Form_Input(
    'input_name_2', // Does not have to match toggle class (!)
    'Input 2',
    'text',
    ''
));

$section->add($group);

$group = new Form_Group('Input 3');
$group->addClass('toggle-example_3 collapse');

$group->add(new Form_Input(
    'input_name_3', // Does not have to match toggle class (!)
    'Input 3',
    'text',
    ''
));

$section->add($group);
```

You can c/p this snippet in any form to check out the behaviour.

**Comment by thanegill** [comment]
Perfect Thanks!
