### ISSUE TITLE
Feature request - button type

### ISSUE THREAD

**Issue by sbeaver-netgate** [SjonHortensius/pfsense#220]
It would be convenient to be able to set the button type for times when 'submit' is not appropriate.
e.g.:

``` php
$btnadv = new Form_Button(
    'btnadv',
    'Advanced',
    null,
    'button'
));

// Or perhaps a little cleaner:

$btnadv = new Form_Button(
    'btnadv',
    'Advanced'
))->setType('button');
```

It would default to 'submit' of course.

**Comment by SjonHortensius** [comment]
The 'advanced' buttons should be removed, this is a typical javascript issue. These buttons don't belong in the php code

**Comment by sbeaver-netgate** [comment]
I find this ambiguous. Do you suggest that the “Advanced” button functionality is removed and that all of the input elements previously controlled by such a button should be displayed at all times, or is it your suggestion that the functionality is retained but implemented in JS (as I have done in the pages converted so far)

## Steve

Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com | www.netgate.com

**Comment by SjonHortensius** [comment]
I suggest the functionality is moved to the global javascripts, and not
implemented per-page. I want to implement this javascript, but that means
you should apply the 'advanced' class to inputs

**Comment by sbeaver-netgate** [comment]
OK. You will see that I have written a number of Javascript functions to hide/show input elements and have used these in a consistent way in several pages recently. Those functioned could/should move to pfSense.js I find this solution to be flexible and effective, buy I’ll wait until you get to those pages for review.

Note that some pages have three or  four “Advanced” buttons controlling the same number of input element groups.

## Steve

Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com | www.netgate.com

**Comment by sbeaver-netgate** [comment]
Thanks Sjon. I very much agree that this is how it should be handled.

[...]

**Comment by SjonHortensius** [comment]
@SanderVanLeeuwen   have implemented this, but am not sure where the 'toggle advanced options' button should go (maybe btn-xs in panel-header?). There is also an issue where the inputs aren't properly hidden onload, any idea how to correct that? This can be tested on /services_dnsmasq.php
