### ISSUE TITLE
Create Custom Input Field for ip address / mask

### ISSUE THREAD

**Issue by thanegill** [SjonHortensius/pfsense#23]
Something similar to this: 
![image](https://cloud.githubusercontent.com/assets/1141680/6548622/488d6174-c5bc-11e4-96fe-f5292fa320f9.png)
(Ignore the '$')

Where there is a text input for the ip address and a drop down for the subnet mask where the '.00' is. 

Would be cleaner than two separate fields.

Just a though as this type of input would be used a lot.

**Comment by thanegill** [comment]
Found what we want.

http://getbootstrap.com/components/#input-groups-buttons-dropdowns

**Comment by SjonHortensius** [comment]
Looks good, but it has two downsides;
- the 'select' prevents the keyboard from being used
- it won't display the selected value

**Comment by thanegill** [comment]
What do you mean prevents keyboard from being used? Right now that dropdown is not a form but an action. So that would need to be ripped out. I was thinking something like this:

http://codepen.io/anon/pen/EadvjB

This is also a good example of where adding raw HTML to a Form_Group would be beneficial. as the span would need to be between the two. #27

**Comment by SjonHortensius** [comment]
Ah, I thought you meant to leave it static html but the codepen looks good and prevents both issues.

As for raw HTML, I'd rather introduce a stricter wrapper for Input+Dropdown so the html can be reused instead of copy/pasted :)

**Comment by thanegill** [comment]
Sounds good. The one thing that I don't like about the codepen is the '/' separator. It seems a bit small and doesn't need to be on a blue background. I'll play around and throw some different css on it.

**Comment by thanegill** [comment]
Take a look at it now. Added some CSS to make it look a little better and more unified.

http://codepen.io/anon/pen/EadvjB

**Comment by SjonHortensius** [comment]
LGTM, any comments from @SanderVanLeeuwen ?

**Comment by thanegill** [comment]
I'm assuming that we would implement this in PHP as a subclass. But of what? Group? Input?

My vote is for group as it is a group itself. But on the other hand it's treated like an input every other way.

On second thought Input would be the right choice.

**Comment by SanderVanLeeuwen** [comment]
I would like to propose a slightly different approach @ http://codepen.io/anon/pen/VYgEdP .

This example uses the default input structure we use, and the existing bootstrap `.input-group-addon` (which is only applied when the input is actually in a group). I've added an `.input-group-inbetween` to remove the double border.

Unfortunately, it's not possible (or at least not cross-browser and platform) to remove the rounded border on the select, so it looks like this on my mac:

![screenshot 2015-03-25 22 07 53](https://cloud.githubusercontent.com/assets/1685007/6835499/754251c0-d33b-11e4-8094-d11bd3444770.png)

**Comment by SjonHortensius** [comment]
I have added the relevant class+css; please comment. The setup allows for other functionality such as Form_IpAddress::setFamily(6) and Form_IpAddress::forceRange(127.0.0.1/24)

**Comment by SanderVanLeeuwen** [comment]
No comment. Looks good :)
