### ISSUE TITLE
Ability to add raw HTML to a `Form_Section`

### ISSUE THREAD

**Issue by thanegill** [SjonHortensius/pfsense#27]
It would be nice to be able to define more complex form fields that do not conform to our classes, or at least don't yet.

**Comment by SjonHortensius** [comment]
Could you give an example? The Forms are prepared for this (that's why they're using toString) but the strictness of classes do have a few benefits ie. the ability to use addClass/removeClass on them

**Comment by thanegill** [comment]
I'm thinking about when you need to wrap a certain element. Thought this might the the hack way to do it and I haven't needed to do it yet. Though you will see something similar in pull request #30 when I'm done with it.

**Comment by thanegill** [comment]
You know I never saw `Form_StaticText`. That might solve all my issues.

I'll close this for now.
