### ISSUE TITLE
Text area form introduces unwanted white space

### ISSUE THREAD

**Issue by sbeaver-netgate** [SjonHortensius/pfsense#270]
Tested with simple string as well as $pconfig data as shown here.

![pfsense_localdomain_-_servicescaptive_portalvouchers](https://cloud.githubusercontent.com/assets/11539696/7914279/12fe98dc-0844-11e5-82ca-9229e54c6c44.png)

(Public key redacted for obvious reasons)

**Comment by SjonHortensius** [comment]
This is exactly what I fixed in b5249aa3d76e59023?

**Comment by sbeaver-netgate** [comment]
OK thanks. I need to fix my git problems before I do anything else :(

> On Jun 1, 2015, at 9:58 AM, SjonHortensius notifications@github.com wrote:
> 
> This is exactly what I fixed in b5249aa https://github.com/SjonHortensius/pfsense/commit/b5249aa3d76e5902339f0e58534607b1af68d86f?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/SjonHortensius/pfsense/issues/270#issuecomment-107496381.

## Steve

Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com mailto:sbeaver@netgate.com | www.netgate.com http://www.netgate.com/

**Comment by sbeaver-netgate** [comment]
I can confirm that you change fixed the issue.

> On Jun 1, 2015, at 9:58 AM, SjonHortensius notifications@github.com wrote:
> 
> This is exactly what I fixed in b5249aa https://github.com/SjonHortensius/pfsense/commit/b5249aa3d76e5902339f0e58534607b1af68d86f?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/SjonHortensius/pfsense/issues/270#issuecomment-107496381.

## Steve

Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com mailto:sbeaver@netgate.com | www.netgate.com http://www.netgate.com/
