### ISSUE TITLE
Better Way to Confirm

### ISSUE THREAD

**Issue by thanegill** [SjonHortensius/pfsense#28]
Instead of `onclick="return confirm('Are you sure');"` there needs to be a better way than this.

A modal popup maybe?

**Comment by SjonHortensius** [comment]
I agree, but confirm() is so enormously convenient compared to any other solution that I'd rather push this towards another release.

There is no simple way to block execution of the a-href if we'd use a modal; it require all completely different setup

**Comment by thanegill** [comment]
How about this? 
http://bootboxjs.com/
or this
https://ethaizone.github.io/Bootstrap-Confirmation/

**Comment by SanderVanLeeuwen** [comment]
Both plugins look good, but I agree with @SjonHortensius that it's not something for this release. I think we should focus on converting all messy template code to the clean bootstrap structure, and add fancy features in a next iteration (same goes for the validation stuff btw.). 

It'll be much easier to add features to the cleaned state. Additionally, the finished state will give us a better overview of what plugins we'll need; influencing the choice. Adding plugins on the go doesn't feel like the wise choice from a quality control perspective.

**Comment by thanegill** [comment]
Sounds good. No scope creep.
