### ISSUE TITLE
Clean Way to Submit a Ajax Form

### ISSUE THREAD

**Issue by thanegill** [SjonHortensius/pfsense#31]
Is there a specific way that I should use to submit a form via ajax? I do need the result to update a form field as well.

Also let me know if questions like these are better suited for an email.

**Comment by SjonHortensius** [comment]
What page are you working on? jQuery has a straight-forward implementation for xhr but maybe we could move this into a non-xhr form for now?

**Comment by thanegill** [comment]
I'm working on interfaces.php still. This is for the add a gateway function.

**Comment by SjonHortensius** [comment]
I'd like to help out but I cannot find that functionality (in interfaces.php?if=lan or anywhere under Interfaces / *); can you point out the specific URL or specific conditions I'm possibly missing?

Alternatively commit it with a fixme and assign it to me to complete the js

**Comment by thanegill** [comment]
[Here](https://github.com/psophis/pfsense/blob/dbe6f6d213b4f2350da92ad6590137ba7ba5ec4f/usr/local/www/interfaces.php#L1578) is what I've gotten so far. It's really messy and I'm not sure how I like the Modal class yet, functionally it works just like a form just with more html around it.

The functionality that I'm look for when adding a new gateway is to popup the modal add submit it via ajax then close on success or show errors on fail.
