### ISSUE TITLE
Remove cancel buttons

### ISSUE THREAD

**Issue by SjonHortensius** [SjonHortensius/pfsense#324]
I have a strong preference to remove all cancel buttons. Browsers have had back-buttons for quite some time and these buttons don't make sense.

If we want them, they should be added globally in From anyway, not manually in all callers

**Comment by SjonHortensius** [comment]
@sbeaver-netgate do you have an opinion on this?

**Comment by sbeaver-netgate** [comment]
I agree for the most part, though the cancel button has slightly different functionality on various pages. Sometimes it is a link to $referer, sometimes to an obvious page (something_edit.php -> something.php), and then again sometimes I think it links to a page that may not be the obvious parent.

If a review shows that all of the use cases can be satisfied by using the "Back" button, I would certainly support the removal of all Cancel buttons.

$form->addCancel();  would also provide a flexible way to do it.

**Comment by SjonHortensius** [comment]
> If a review shows that all of the use cases can be satisfied by using the "Back" button, I would certainly support the removal of all Cancel buttons.

It does, so we should

**Comment by sbeaver-netgate** [comment]
I’ll take care of that tomorrow in a single feature branch.

> On Jul 9, 2015, at 9:26 AM, SjonHortensius notifications@github.com wrote:
> 
> If a review shows that all of the use cases can be satisfied by using the "Back" button, I would certainly support the removal of all Cancel buttons.
> 
> It does, so we should
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/SjonHortensius/pfsense/issues/324#issuecomment-119964152.

## Steve

Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com mailto:sbeaver@netgate.com | www.netgate.com http://www.netgate.com/
