### ISSUE TITLE
Clear Formatting Guide

### ISSUE THREAD

**Issue by thanegill** [SjonHortensius/pfsense#33]
This is what I'm following. Just so we're all on the same page. Though what is said in the README about tabstops precedes this:

https://doc.pfsense.org/index.php/Developer_Style_Guide

and using [K&R style](https://en.wikipedia.org/wiki/Indent_style#K.26R_style) as listed in the style guide.

**Comment by SjonHortensius** [comment]
You are right; we are following different standards. This has various reasons, one of which is that I normally use a different standard (which is based on http://framework.zend.com/manual/1.12/en/coding-standard.html). However, given the enormous amount of work that also needs to be done I prefer not to worry about this too much.

I'll accept both K&R or ZF code; if we refrain from refactoring each-other's code _just for consistency of whitespace_ that'll work fine. Whitespace is easy to correct automagically afterwards and I don't want it getting in the way of completing this rewrite.

**Comment by thanegill** [comment]
Sounds good. Can we put this somewhere in the README for clarity for new contributors? We should also add that we don't expect any logic rewrite or at least some mention of the scope of the project.
