### ISSUE TITLE
Upstream security issues

### ISSUE THREAD

**Issue by sbeaver-netgate** [SjonHortensius/pfsense#336]
The pfSense maintainers have provided a list of 30 or so security changes related to the web GUI that have been made since the start of the Bootstrap project.

I have reviewed each of the changes and found that only trivial changes were required to a few files. Those have been submitted by PR 335.

**Comment by SjonHortensius** [comment]
Thanks; there is no need to duplicate the PR in this issue.

Fixed in #335

**Comment by sbeaver-netgate** [comment]
My plan was to attach my working spreadsheet to the issue, but I was unable to do that :(

## Steve

Als ik kan
