### ISSUE TITLE
Bootstrap conversion progress table

### ISSUE THREAD

**Issue by sbeaver-netgate** [SjonHortensius/pfsense#40]
## Bootstrap Conversion Progress

Use this table to list the PHP pages that have been converted to bootstrap, those that have yet to be converted, and those that are currently being worked on. 

The table can be generated by running this bash script on the directory in which the php files are located. e.g.:

``` bash
   mktable.sh pfsense-bootstrap/usr/local/www
```

``` bash
#!/bin/bash
# mktable.sh

# Generate a table in GitHub markdown showing each php file and whether it has been converted to bootstrap yet
# $1 = path to pfSense usr/local/www directory
# Completed files are assumed to have foot.inc included

pushd $1

printf "|%-45s|%-25s|%-24s|%-60s|\r\n" "Page/file" "Status" "User" "Comments" 
printf "|---------------------------------------------|:-------------------------:|------------------------|------------------------------------------------------------|\r\n"

FILES=$(ls -1 *.php)

for F in $FILES ; do
   printf "|%-45s|" $F

   if(grep foot.inc $F >/dev/null 2>&1 ) ; then
      printf "%-25s" ":white_check_mark:"
   else
      printf "%25s" "                  "
   fi

   printf "|%24s|%60s|\r\n" " " " "

done  

popd
```

You can then copy/paste the script output into this file. (Is that recursive?)

Use the :white_check_mark: emoji (`:white_check_mark:`) to show that the bootstrap conversion is complete
Use the :arrows_counterclockwise: emoji (`:arrows_counterclockwise:`) to show that the bootstrap conversion is in progress
### PHP file status

| Page/file | Status | User | Comments |
| --- | :-: | --- | --- |
| bandwidth_by_ip.php |  |  |  |
| carp_status.php | :white_check_mark: |  |  |
| crash_reporter.php | :white_check_mark: |  |  |
| diag_arp.php | :white_check_mark: |  |  |
| diag_authentication.php | :white_check_mark: |  |  |
| diag_backup.php | :white_check_mark: |  |  |
| diag_confbak.php | :white_check_mark: |  |  |
| diag_defaults.php | :white_check_mark: |  |  |
| diag_dns.php | :arrows_counterclockwise: | Steve Beaver | Fixed upstream issue causing add alias funtion to fail |
| diag_dump_states.php |  |  |  |
| diag_dump_states_sources.php |  |  |  |
| diag_gmirror.php |  |  |  |
| diag_ipsec.php |  |  |  |
| diag_ipsec_leases.php |  |  |  |
| diag_ipsec_sad.php |  |  |  |
| diag_ipsec_spd.php |  |  |  |
| diag_ipsec_xml.php |  |  |  |
| diag_limiter_info.php |  |  |  |
| diag_logs.php |  |  |  |
| diag_logs_auth.php |  |  |  |
| diag_logs_dhcp.php |  |  |  |
| diag_logs_filter.php |  |  |  |
| diag_logs_filter_dynamic.php |  |  |  |
| diag_logs_filter_summary.php |  |  |  |
| diag_logs_gateways.php |  |  |  |
| diag_logs_ipsec.php |  |  |  |
| diag_logs_ntpd.php |  |  |  |
| diag_logs_openvpn.php |  |  |  |
| diag_logs_ppp.php |  |  |  |
| diag_logs_relayd.php |  |  |  |
| diag_logs_resolver.php |  |  |  |
| diag_logs_routing.php |  |  |  |
| diag_logs_settings.php |  |  |  |
| diag_logs_vpn.php |  |  |  |
| diag_logs_wireless.php |  |  |  |
| diag_nanobsd.php |  |  |  |
| diag_ndp.php |  |  |  |
| diag_packet_capture.php |  |  |  |
| diag_patterns.php |  |  |  |
| diag_pf_info.php |  |  |  |
| diag_ping.php |  |  |  |
| diag_pkglogs.php |  |  |  |
| diag_resetstate.php |  |  |  |
| diag_routes.php |  |  |  |
| diag_smart.php |  |  |  |
| diag_sockets.php |  |  |  |
| diag_states_summary.php |  |  |  |
| diag_system_activity.php |  |  |  |
| diag_system_pftop.php |  |  |  |
| diag_tables.php |  |  |  |
| diag_testport.php |  |  |  |
| diag_traceroute.php |  |  |  |
| easyrule.php |  |  |  |
| edit.php |  |  |  |
| exec.php |  |  |  |
| firewall_aliases.php |  |  |  |
| firewall_aliases_edit.php |  |  |  |
| firewall_aliases_import.php |  |  |  |
| firewall_nat.php |  |  |  |
| firewall_nat_1to1.php |  |  |  |
| firewall_nat_1to1_edit.php |  |  |  |
| firewall_nat_edit.php |  |  |  |
| firewall_nat_npt.php |  |  |  |
| firewall_nat_npt_edit.php |  |  |  |
| firewall_nat_out.php |  |  |  |
| firewall_nat_out_edit.php |  |  |  |
| firewall_rules.php | :white_check_mark: |  |  |
| firewall_rules_edit.php | :white_check_mark: |  |  |
| firewall_schedule.php |  |  |  |
| firewall_schedule_edit.php |  |  |  |
| firewall_shaper.php |  |  |  |
| firewall_shaper_layer7.php |  |  |  |
| firewall_shaper_queues.php |  |  |  |
| firewall_shaper_vinterface.php |  |  |  |
| firewall_shaper_wizards.php |  |  |  |
| firewall_virtual_ip.php |  |  |  |
| firewall_virtual_ip_edit.php |  |  |  |
| getserviceproviders.php |  |  |  |
| getstats.php |  |  |  |
| graph.php |  |  |  |
| graph_cpu.php |  |  |  |
| halt.php |  |  |  |
| help.php |  |  |  |
| ifstats.php |  |  |  |
| index.php | :white_check_mark: |  |  |
| interfaces.php |  |  |  |
| interfaces_assign.php | :white_check_mark: |  |  |
| interfaces_bridge.php |  |  |  |
| interfaces_bridge_edit.php |  |  |  |
| interfaces_gif.php |  |  |  |
| interfaces_gif_edit.php |  |  |  |
| interfaces_gre.php |  |  |  |
| interfaces_gre_edit.php |  |  |  |
| interfaces_groups.php |  |  |  |
| interfaces_groups_edit.php |  |  |  |
| interfaces_lagg.php |  |  |  |
| interfaces_lagg_edit.php |  |  |  |
| interfaces_ppps.php |  |  |  |
| interfaces_ppps_edit.php |  |  |  |
| interfaces_qinq.php |  |  |  |
| interfaces_qinq_edit.php |  |  |  |
| interfaces_vlan.php | :white_check_mark: |  |  |
| interfaces_vlan_edit.php | :white_check_mark: |  |  |
| interfaces_wireless.php |  |  |  |
| interfaces_wireless_edit.php |  |  |  |
| license.php |  |  |  |
| load_balancer_monitor.php |  |  |  |
| load_balancer_monitor_edit.php |  |  |  |
| load_balancer_pool.php |  |  |  |
| load_balancer_pool_edit.php |  |  |  |
| load_balancer_relay_action.php |  |  |  |
| load_balancer_relay_action_edit.php |  |  |  |
| load_balancer_relay_protocol.php |  |  |  |
| load_balancer_relay_protocol_edit.php |  |  |  |
| load_balancer_setting.php |  |  |  |
| load_balancer_virtual_server.php |  |  |  |
| load_balancer_virtual_server_edit.php |  |  |  |
| pkg.php |  |  |  |
| pkg_edit.php |  |  |  |
| pkg_mgr.php | :white_check_mark: |  |  |
| pkg_mgr_install.php | :white_check_mark: |  |  |
| pkg_mgr_installed.php | :white_check_mark: |  |  |
| pkg_mgr_settings.php |  |  |  |
| reboot.php |  |  |  |
| restart_httpd.php |  |  |  |
| services_captiveportal.php |  |  |  |
| services_captiveportal_filemanager.php |  |  |  |
| services_captiveportal_hostname.php |  |  |  |
| services_captiveportal_hostname_edit.php |  |  |  |
| services_captiveportal_ip.php |  |  |  |
| services_captiveportal_ip_edit.php |  |  |  |
| services_captiveportal_mac.php |  |  |  |
| services_captiveportal_mac_edit.php |  |  |  |
| services_captiveportal_vouchers.php |  |  |  |
| services_captiveportal_vouchers_edit.php |  |  |  |
| services_captiveportal_zones.php |  |  |  |
| services_captiveportal_zones_edit.php |  |  |  |
| services_dhcp.php |  |  |  |
| services_dhcp_edit.php |  |  |  |
| services_dhcp_relay.php |  |  |  |
| services_dhcpv6.php |  |  |  |
| services_dhcpv6_edit.php |  |  |  |
| services_dhcpv6_relay.php |  |  |  |
| services_dnsmasq.php |  |  |  |
| services_dnsmasq_domainoverride_edit.php |  |  |  |
| services_dnsmasq_edit.php |  |  |  |
| services_dyndns.php |  |  |  |
| services_dyndns_edit.php |  |  |  |
| services_igmpproxy.php |  |  |  |
| services_igmpproxy_edit.php |  |  |  |
| services_ntpd.php |  |  |  |
| services_ntpd_gps.php |  |  |  |
| services_ntpd_pps.php |  |  |  |
| services_rfc2136.php |  |  |  |
| services_rfc2136_edit.php |  |  |  |
| services_router_advertisements.php |  |  |  |
| services_snmp.php |  |  |  |
| services_unbound.php |  |  |  |
| services_unbound_acls.php |  |  |  |
| services_unbound_advanced.php |  |  |  |
| services_unbound_domainoverride_edit.php |  |  |  |
| services_unbound_host_edit.php |  |  |  |
| services_wol.php |  |  |  |
| services_wol_edit.php |  |  |  |
| stats.php |  |  |  |
| status.php |  |  |  |
| status_captiveportal.php |  |  |  |
| status_captiveportal_expire.php |  |  |  |
| status_captiveportal_test.php |  |  |  |
| status_captiveportal_voucher_rolls.php |  |  |  |
| status_captiveportal_vouchers.php |  |  |  |
| status_dhcp_leases.php |  |  |  |
| status_dhcpv6_leases.php |  |  |  |
| status_filter_reload.php |  |  |  |
| status_gateway_groups.php |  |  |  |
| status_gateways.php |  |  |  |
| status_graph.php |  |  |  |
| status_graph_cpu.php |  |  |  |
| status_interfaces.php |  |  |  |
| status_lb_pool.php |  |  |  |
| status_lb_vs.php |  |  |  |
| status_ntpd.php |  |  |  |
| status_openvpn.php |  |  |  |
| status_queues.php |  |  |  |
| status_rrd_graph.php |  |  |  |
| status_rrd_graph_img.php |  |  |  |
| status_rrd_graph_settings.php |  |  |  |
| status_services.php |  |  |  |
| status_upnp.php |  |  |  |
| status_wireless.php |  |  |  |
| system.php | :white_check_mark: |  |  |
| system_advanced_admin.php | :white_check_mark: |  |  |
| system_advanced_firewall.php | :white_check_mark: |  |  |
| system_advanced_misc.php | :white_check_mark: |  |  |
| system_advanced_network.php | :white_check_mark: |  |  |
| system_advanced_notifications.php | :white_check_mark: |  |  |
| system_advanced_sysctl.php |  |  |  |
| system_authservers.php |  |  |  |
| system_camanager.php |  |  |  |
| system_certmanager.php |  |  |  |
| system_crlmanager.php |  |  |  |
| system_firmware.php |  |  |  |
| system_firmware_auto.php |  |  |  |
| system_firmware_check.php |  |  |  |
| system_firmware_restorefullbackup.php |  |  |  |
| system_firmware_settings.php |  |  |  |
| system_gateway_groups.php |  |  |  |
| system_gateway_groups_edit.php |  |  |  |
| system_gateways.php |  |  |  |
| system_gateways_edit.php |  |  |  |
| system_groupmanager.php |  |  |  |
| system_groupmanager_addprivs.php |  |  |  |
| system_hasync.php |  |  |  |
| system_routes.php |  |  |  |
| system_routes_edit.php |  |  |  |
| system_usermanager.php |  |  |  |
| system_usermanager_addprivs.php |  |  |  |
| system_usermanager_passwordmg.php |  |  |  |
| system_usermanager_settings.php |  |  |  |
| system_usermanager_settings_ldapacpicker.php |  |  |  |
| system_usermanager_settings_test.php |  |  |  |
| uploadconfig.php |  |  |  |
| vpn_ipsec.php |  |  |  |
| vpn_ipsec_keys.php |  |  |  |
| vpn_ipsec_keys_edit.php |  |  |  |
| vpn_ipsec_mobile.php | :white_check_mark: |  |  |
| vpn_ipsec_phase1.php |  |  |  |
| vpn_ipsec_phase2.php |  |  |  |
| vpn_ipsec_settings.php |  |  |  |
| vpn_l2tp.php | :white_check_mark: |  |  |
| vpn_l2tp_users.php | :white_check_mark: |  |  |
| vpn_l2tp_users_edit.php | :white_check_mark: |  |  |
| vpn_openvpn_client.php |  |  |  |
| vpn_openvpn_csc.php |  |  |  |
| vpn_openvpn_server.php |  |  |  |
| vpn_pppoe.php |  |  |  |
| vpn_pppoe_edit.php |  |  |  |
| vpn_pptp.php |  |  |  |
| vpn_pptp_users.php |  |  |  |
| vpn_pptp_users_edit.php |  |  |  |
| wizard.php |  |  |  |
| xmlrpc.php |  |  |  |

**Comment by SjonHortensius** [comment]
Looks good! If you want to create a PR I"ll merge it.

**Comment by sbeaver-netgate** [comment]
OK

**Comment by sbeaver-netgate** [comment]
I guess emoji don’t work when viewing a .md file :(

**Comment by SjonHortensius** [comment]
Maybe referencing the image directly works?

**Comment by SanderVanLeeuwen** [comment]
Why not just use the emoji as character? Chrome on OS X supports it; not sure if it's also supported on other platforms though. Check http://www.fileformat.info/info/emoji/browsertest.htm .

✅ 🙈

**Comment by thanegill** [comment]
This looks great! But I don't really want to submit a pull request every time I'm starting on a page, can this go in a wiki instead?

**Comment by sbeaver-netgate** [comment]
Sure. Sjon asked me to commit it, but I will be putting it in a Wiki as well later today (after I have made the emoji work properly :)

I will also be starting a Wiki section to document units tests. Each time we convert a GUI page I’d like there to be some notes on how to test the features on that page. Since we are touching every php file anyway now seems like a good time to start that practice. With any luck by the time we get to the end of the project we will have a complete set of test cases that we can use for regression testing in the future.

Steve

**Comment by SjonHortensius** [comment]
@psophis If you prefer that I can move it to a wiki. I value the progress more for its checkboxes so we have an overview of what is done and what not. As for the claiming of pages for conversion, I think the issues we've used so far work fine

@sbeaver-netgate If you want to document your testing; go ahead, but I think it doesn't belong in this repo which is focused on converting to Bootstrap :)

**Comment by sbeaver-netgate** [comment]
Hi Sjon,

OK. I’m happy to do whatever you prefer. Just a suggestion. I will be creating unit test documents as I work on each page and was thinking about the best place to house those. A Wiki page on pfSense/bootstrap seems like the best place, but I can also use a wiki page at wiki.pfsense.org http://wiki.pfsense.org/ or anywhere else JimT prefers.

Thanks for tolerating my “work” this week. As I’m sure you can tell you can tell this is my first exposure to git and/or GitHub( I am a long time SVN and AccuRev user)  :(

I’ll figure it out before too long.

## Steve

Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com | www.netgate.com

**Comment by SjonHortensius** [comment]
I think tests will be very beneficial, but I don't have time for it (I do obviously test my changes, but documenting procedures takes time). I'd rather focus on the code.

I understand getting used to git takes some time, don't worry about it. :+1:
