### ISSUE TITLE
Need a interface + javascript that duplicates a Group

### ISSUE THREAD

**Issue by SjonHortensius** [SjonHortensius/pfsense#45]
Should be able to append name[]; this implies some backend changes because most lists use dns1, dns2, dns3 ... etc; but I prefer dns[], dns[], dns[] instead.

A generic plus-button with logic would be great; could be integrated as Input::enableUserDuplication($max)

**Comment by SjonHortensius** [comment]
Should also support deletion (always leave at least one behind). Should work on groups, not inputs (should duplicate all inputs in a group)

**Comment by SjonHortensius** [comment]
@SanderVanLeeuwen please review (Firewall>Aliases will be a good place to showcase this)

Also, it needs some layout love. Some tweaks (related to the plus button) also needed pending final layout

**Comment by SanderVanLeeuwen** [comment]
Looks good! I do have a suggestion for layout; wouldn't it be better to use small buttons? This also explains that the plus is not a plus but rather a duplicate button.

![screenshot 2015-04-19 21 45 55](https://cloud.githubusercontent.com/assets/1685007/7221069/aeff345e-e6dd-11e4-9c6c-49b249421c89.png)

**Comment by SjonHortensius** [comment]
The increased text-length does force the buttons onto a new line, this 'd look a lot better if the buttons could be appended to the current group, and not cause a second line...

**Comment by SanderVanLeeuwen** [comment]
Hm, placing those buttons on a new line was on purpose to be honest. It's an option to append them to the same line, but that would require stealing column width from one of the inputs. Or place them back in front of the line?
