### ISSUE TITLE
Consistent table and action-button styling

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [SjonHortensius/pfsense#51]
Tables should be wrapped in a `table-responsive` and action buttons in a `nav.action-buttons`.

**Comment by SjonHortensius** [comment]
I still have a minor preference for a javascript that applies class=table plus this wrapper to all tables.

It enforces consistency while keeping the amount of manual work to a minimum

**Comment by SanderVanLeeuwen** [comment]
As long as we're touching every file or template, it feels like a quick win to add the relevant HTML instead of waiting for javascript to fix pages after they're loaded. I could very well be a difference of opinion which we're never going to agree on though ;)
